x-veld:
  code:
    description: "This code veld encapsulates and veldifies the xmltokenize script. All its 
      config here are passed down to the script. For more information on its usage and config, 
      see: https://github.com/ufal/teitok-tools?tab=readme-ov-file#xmltokenize"
    topic:
      - NLP
      - ETL
      - Tokenization
      - Universal Dependencies

    input:
      - volume: /veld/input/
        file_type: xml
        environment_var: in_xml_file
        description: "The xml file to be tokenized"

    output:
      - volume: /veld/output/
        file_type: xml
        environment_var: out_xml_file
        description: "The output tokenized xml"

    config:
      - environment_var:  textnode
        description: "what to use as the text body to tokenize"
        var_type: str
      - environment_var: exclude
        description: "elements not to tokenize"
        var_type: str
        optional: true
      - environment_var: enumerate
        description: "provide a unique ID to each token"
        var_type: bool
        default: false
        optional: true
      - environment_var: segment
        description: "split into sentences (1=yes, 2=only) - only for TEI files"
        var_type: int
        optional: true

services:
  veld_xmltokenize:
    build: .
    volumes:
      - ./:/veld/code/
    command: bash /veld/code/veld_xmltokenize.sh
    environment:
      in_xml_file: null
      out_xml_file: null
      textnode: null
      tok: null
      exclude: null
      enumerate: false
      segment: null 

