x-veld:
  code:
    description: "This code veld encapsulates and veldifies the xmltokenize script. All its 
      settings here are passed down to the script. For more information on its usage and settings, 
      see: https://github.com/ufal/teitok-tools?tab=readme-ov-file#xmltokenize"
    topics:
      - NLP
      - ETL
      - tokenization
      - universal dependencies

    inputs:
      - volume: /veld/input/
        file_type: xml
        environment: in_xml_file
        description: "The xml file to be tokenized"

    outputs:
      - volume: /veld/output/
        file_type: xml
        environment: out_xml_file
        description: "The output tokenized xml"

    settings:
      - environment:  textnode
        description: "what to use as the text body to tokenize"
        env_type: str
      - environment: exclude
        description: "elements not to tokenize"
        env_type: str
        optional: true
      - environment: enumerate
        description: "provide a unique ID to each token"
        env_type: bool
        default: false
        optional: true
      - environment: segment
        description: "split into sentences (1=yes, 2=only) - only for TEI files"
        env_type: int
        optional: true

services:
  veld_xmltokenize:
    build: .
    volumes:
      - ./:/veld/code/
    command: ./veld_xmltokenize.sh
    environment:
      in_xml_file: null
      out_xml_file: null
      textnode: null
      tok: null
      exclude: null
      enumerate: false
      segment: null 

